language: python
python:
- 2.7
- 3.6
script:
- python setup.py test
deploy:
  provider: pypi
  user: jkawamoto
  password:
    secure: eId+eknN0qL8stCbqwB6HcxN+YyMC3uglVtVvkpNlQDW3V6NGfLBFclBmtEZB2PGyw3JGeoBwug7KqdAhXficEBWE4oOtb4yjzEm+ViR/fuqAOHau2uPpZ5QQQDJJgx3/C3y9MvWopjkivCfCug88VZSSPTe3TYOswEun7SwLxmW16RVsqPF3ghvS2lsBvZXw5BKNqmu5OYy0KzxL0vsrQTQHuc0SNyKqpVy5vCcFpY9IgY1PTLkE5LYMW+51X5MNPF3N+1sAVZxXapIbovBmz/ubfNradZyCWN/BNXKf19k3G4POcOLyruaEpUnroXLa0NHaLsWBFi7tLpPhvYNn/ypSZf1JUTyXoMbWWpHwaHqV1JrK0JHjYQLTefsvgwyvC59wpwzaX+SJVeODu5TvOGeDSYnbwGQyOYucUWJV8avOv31bHWqT9OKi5dWltCGZD8aCW+ghyTA80bKMX7XRloIgbJzs/t1hFwYbNx+vTz3P2iin2ndAU/grYKkVCVb4LrydMltteSvGPI8HWw8OfmyBvh2rORoGRkD0T1xD8YuCAg4epdtq54vzSkzVR1DqmU2jKIJO2Z8jnigIqbXgUsE6d431SSFZyniCf1oBwh0cSqlomNF96CRHWU9DpX59aME9Ad/IgM3lJ+u4eFWfqFzdFq3qJDzM2M6DskR2Pw=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: rgmining/ria
